<a href="https://colab.research.google.com/github/masonfarley18/CPSC-392/blob/main/All_the_stuff_you_need_to_know(python).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import necessary packages here
import warnings
warnings.filterwarnings('ignore')

1. Load the pandas library, and alias it so you can use `pd` instead of typing `pandas` each time you need to access the package.

2. Load the penguin and titanic datasets from GitHub. Store them in `penguins` and `titanic` respectively.

In [3]:
import pandas as pd

penguins = pd.read_csv("https://raw.githubusercontent.com/ywen2021/CPSC392/main/Data/penguins.csv")
titanic = pd.read_csv("https://raw.githubusercontent.com/ywen2021/CPSC392/main/Data//titanic.csv")

3. Print the head (first 5 or 6 rows) of each data set.

In [4]:
penguins

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,63,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,64,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,65,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,66,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,67,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

4. Store the sex column from the titanic dataset in the variable `sex`. Print it.

In [5]:
sex = titanic["sex"]
sex = titanic.sex

In [6]:
penguins_10 = penguins.iloc[9]
penguins_10

Unnamed: 0                   9
species                 Adelie
island               Torgersen
bill_length_mm            42.0
bill_depth_mm             20.2
flipper_length_mm        190.0
body_mass_g             4250.0
sex                        NaN
year                      2007
Name: 9, dtype: object

In [8]:
passenger4_and_12 = titanic.iloc[[3,11]]
passenger4_and_12

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
3,3,1,1,female,35.0,1,0,53.10,S,First,woman,False,C,Southampton,yes,False
11,11,1,1,female,58.0,0,0,26.55,S,First,woman,False,C,Southampton,yes,True

In [10]:
mean_age = (titanic.loc[:, ["age"]].sum()) / len(titanic)
mean_age

age    23.799293
dtype: float64

In [12]:
penguins["bill_ratio"] = penguins.loc[:,"bill_length_mm"] / penguins.loc[:,"bill_depth_mm"]
penguins.loc[:, "bill_ratio"]

0      2.090909
1      2.270115
2      2.238889
3           NaN
4      1.901554
         ...
339    2.818182
340    2.403315
341    2.725275
342    2.673684
343    2.684492
Name: bill_ratio, Length: 344, dtype: float64

In [27]:
unfiltered = pd.DataFrame(penguins)
lil_boys = unfiltered[penguins['body_mass_g'] < 4000]
lil_boys[0:4]

,Unnamed: 0,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,bill_ratio
0,0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,2.090909
1,1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,2.270115
2,2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,2.238889
4,4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,1.901554

In [34]:
unfiltered = pd.DataFrame(penguins)

adelie_df = unfiltered[unfiltered['species'] == 'Adelie']
bl_Adelie = adelie_df["bill_length_mm"].sum() / len(adelie_df)

chinstrap_df = unfiltered[unfiltered['species'] == 'Chinstrap']
bl_Chinstrap = chinstrap_df["bill_length_mm"].sum() / len(chinstrap_df)

gentoo_df = unfiltered[unfiltered['species'] == 'Gentoo']
bl_Gentoo = gentoo_df["bill_length_mm"].sum() / len(gentoo_df)

print(bl_Adelie)
print(bl_Chinstrap)
print(bl_Gentoo)

38.536184210526315
48.83382352941177
47.12177419354838

In [37]:
first_df = titanic[titanic['class'] == 'First']
first_prop_survivors = len(first_df[first_df['survived'] == 1]) / len(first_df)

second_df = titanic[titanic['class'] == 'Second']
second_prop_survivors = len(second_df[second_df['survived'] == 1]) / len(second_df)

third_df = titanic[titanic['class'] == 'Third']
third_prop_survivors = len(third_df[third_df['survived'] == 1]) / len(third_df)

print(first_prop_survivors)
print(second_prop_survivors)
print(third_prop_survivors)

0.6296296296296297
0.47282608695652173
0.24236252545824846

In [40]:
male_df = titanic[titanic['sex'] == 'male']
male_fare_mean = (male_df.loc[:, 'fare'].sum()) / len(male_df)

female_df = titanic[titanic['sex'] == 'female']
female_fare_mean = (female_df.loc[:, 'fare'].sum()) / len(female_df)

print(male_fare_mean)
print(female_fare_mean)

25.523893414211443
44.47981783439491

In [43]:
small_penguin = penguins.loc[:, ['bill_length_mm', 'species', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]
small_penguin

     bill_length_mm    species  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1     Adelie           18.7              181.0       3750.0
1              39.5     Adelie           17.4              186.0       3800.0
2              40.3     Adelie           18.0              195.0       3250.0
3               NaN     Adelie            NaN                NaN          NaN
4              36.7     Adelie           19.3              193.0       3450.0
..              ...        ...            ...                ...          ...
339            55.8  Chinstrap           19.8              207.0       4000.0
340            43.5  Chinstrap           18.1              202.0       3400.0
341            49.6  Chinstrap           18.2              193.0       3775.0
342            50.8  Chinstrap           19.0              210.0       4100.0
343            50.2  Chinstrap           18.7              198.0       3775.0

[344 rows x 5 columns]

In [46]:
small_penguin = small_penguin.drop(columns=['flipper_length_mm'])
small_penguin

     bill_length_mm    species  bill_depth_mm  body_mass_g
0              39.1     Adelie           18.7       3750.0
1              39.5     Adelie           17.4       3800.0
2              40.3     Adelie           18.0       3250.0
3               NaN     Adelie            NaN          NaN
4              36.7     Adelie           19.3       3450.0
..              ...        ...            ...          ...
339            55.8  Chinstrap           19.8       4000.0
340            43.5  Chinstrap           18.1       3400.0
341            49.6  Chinstrap           18.2       3775.0
342            50.8  Chinstrap           19.0       4100.0
343            50.2  Chinstrap           18.7       3775.0

[344 rows x 4 columns]

In [47]:
small_penguin.info()
small_penguin.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bill_length_mm  342 non-null    float64
 1   species         344 non-null    object
 2   bill_depth_mm   342 non-null    float64
 3   body_mass_g     342 non-null    float64
dtypes: float64(3), object(1)
memory usage: 10.9+ KB

       bill_length_mm  bill_depth_mm  body_mass_g
count      342.000000     342.000000   342.000000
mean        43.921930      17.151170  4201.754386
std          5.459584       1.974793   801.954536
min         32.100000      13.100000  2700.000000
25%         39.225000      15.600000  3550.000000
50%         44.450000      17.300000  4050.000000
75%         48.500000      18.700000  4750.000000
max         59.600000      21.500000  6300.000000

In [49]:
grouped = small_penguin.groupby('species')['bill_length_mm'].agg('mean')
print(grouped)

species
Adelie       38.791391
Chinstrap    48.833824
Gentoo       47.504878
Name: bill_length_mm, dtype: float64

In [51]:
small_penguin = small_penguin.loc[(small_penguin['bill_length_mm'] < 39) & (small_penguin['bill_depth_mm'] < 18)]
small_penguin

     bill_length_mm species  bill_depth_mm  body_mass_g
6              38.9  Adelie           17.8       3625.0
10             37.8  Adelie           17.1       3300.0
11             37.8  Adelie           17.3       3700.0
15             36.6  Adelie           17.8       3700.0
24             38.8  Adelie           17.2       3800.0
34             36.4  Adelie           17.0       3325.0
44             37.0  Adelie           16.9       3000.0
48             36.0  Adelie           17.9       3450.0
52             35.0  Adelie           17.9       3450.0
58             36.5  Adelie           16.6       2850.0
60             35.7  Adelie           16.9       3150.0
62             37.6  Adelie           17.0       3600.0
64             36.4  Adelie           17.1       2850.0
66             35.5  Adelie           16.2       3350.0
68             35.9  Adelie           16.6       3050.0
74             35.5  Adelie           17.5       3700.0
78             36.2  Adelie           16.1       3550.0
80             34.6  Adelie           17.2       3200.0
84             37.3  Adelie           17.8       3350.0
92             34.0  Adelie           17.1       3400.0
94             36.2  Adelie           17.3       3300.0
98             33.1  Adelie           16.1       2900.0
100            35.0  Adelie           17.9       3725.0
102            37.7  Adelie           16.0       3075.0
106            38.6  Adelie           17.2       3750.0
108            38.1  Adelie           17.0       3175.0
110            38.1  Adelie           16.5       3825.0
116            38.6  Adelie           17.0       2900.0
118            35.7  Adelie           17.0       3350.0
120            36.2  Adelie           17.2       3150.0
124            35.2  Adelie           15.9       3050.0
126            38.8  Adelie           17.6       3275.0
130            38.5  Adelie           17.9       3325.0
134            38.1  Adelie           17.6       3425.0
136            35.6  Adelie           17.5       3175.0
138            37.0  Adelie           16.5       3400.0
142            32.1  Adelie           15.5       3050.0
144            37.3  Adelie           16.8       3000.0
148            36.0  Adelie           17.8       3450.0
150            36.0  Adelie           17.1       3700.0

5. Store the 10th row from the penguin dataset in the variable `penguins_10`. Print it.

6. Grab the 4th,12th rows of the titanic dataset and store them in the variable `passenger4_and_12`. Print it.

7. Store the mean age of titanic passengers in the variable `mean_age`, print it.

8. Create a new column in `penguins` called `bill_ratio` for the penguin dataset that contains the ratio of bill length to bill depth (in otherwords bill length divided by bill depth). Print out this column.

9. Create a new data frame called `lil_boys` that only contains penguins that have a body mass less than 4000 grams. Print the first 4 rows of this dataframe.

10. What is the mean bill length for each species of penguin? Store the means in the variables `bl_Adelie`, `bl_Chinstrap` and `bl_Gentoo` respectively. Print them out.

11. Which class from the titanic dataset had the highest proportion of surviors? Print out the proportion of people who survived for each class.

12. Is there a difference in the average fare paid between males and females in the titanic dataset? Use pandas to find your answer.

13. Create a dataframe called `small_penguin` that has all the rows from `penguins` but only the columns `bill_length_mm`, `species` ,`bill_depth_mm` , `flipper_length_mm` , and `body_mass_g`
14. delelte `flipper_length_mm` from dataframe `small_penguin`

15. Using .info() and .describe() on dataframe `small_penguin` to see what you can get
16. use groupby on dataframe `small_penguin` to get species average bill length
17. get data from `small_penguin` where bill length less than 39 and bill depth less than 18, print it